name: app_salao_pro
description: Sistema de agendamento para salões de beleza
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3   # atualizado

  # Supabase
  supabase_flutter: ^1.10.4
  image_picker: ^1.1.1
  image: ^4.7.1          # atualizado

  # Variáveis de ambiente
  flutter_dotenv: ^5.1.0

  # Firebase
  #firebase_core: ^2.30.0
  #firebase_auth: ^4.19.2cls
  
  #cloud_firestore: ^4.17.5

  # Calendário
  table_calendar: ^3.2.0  # atualizado

  # Formatação de moeda e telefone
  flutter_multi_formatter: ^2.13.10

  # Internacionalização
  intl: ^0.20.2           # atualizado

  # Material Design
  cupertino_icons: ^1.0.6

  mask_text_input_formatter: ^2.4.0

  # Links (migrar futuramente para app_links)
  uni_links: ^0.5.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # atualizado
  mocktail: ^1.0.0
  flutter_launcher_icons: ^0.14.4  # atualizado

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo_salao_pro.png
    - assets/logo_salao_pro_horiz.png
    - assets/logo_salao_pro_horiz_trans.png
    - assets/icon.png
  
dependency_overrides:
  sign_in_with_apple:
    path: packages/sign_in_with_apple_fake
